# This workflow migrates repositories from one organization to another organization on GHEC
#
# To use this workflow, you will need to:
# 1. Create a GitHub PAT with the `admin:org`,`repo` scope and store it as a secret in the source organization.
# 2. Create a GitHub PAT with the `admin:org`,`repo` scope and store it as a secret in the destination organization.
# 3. Create a secret at repository level with the name `GHEC_USER_NAME` and the value of the GitHub username of the user who created the PATs.
# 4. Create a secret at repository level with the name `GHEC_USER_PAT` and the value of the GitHub PAT of the user who created the PATs.
# 5. Create a variable at repository level with the name `GHEC_SOURCE_ORG_NAME` and the value of the source organization name.
# 6. Create a variable at repository level with the name `GHEC_TARGET_ORG_NAME` and the value of the target organization name.
# 7. Create a variable at repository level with the name `GHEC_MAIN_BRANCH` and the value of the main branch name.

name: Migrate GHEC Org1 repo to GHEC Org2 repo

on: workflow_dispatch

env:
  GHEC_USER_NAME: ${{ secrets.GHEC_USER_NAME }}
  GHEC_USER_PAT: ${{ secrets.GHEC_USER_PAT }}
  GHEC_SOURCE_ORG_NAME: ${{ vars.GHEC_SOURCE_ORG_NAME }}
  GHEC_TARGET_ORG_NAME: ${{ vars.GHEC_TARGET_ORG_NAME }}
  GHEC_MAIN_BRANCH: ${{ vars.GHEC_MAIN_BRANCH }}

jobs:
  GHES-to-GitHub:
    name: Migrate from GHES to GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Migrate repos
        run: |
          chmod a+x ./migration-scripts/migrate-repos-from-list-base-ghec2ghec.sh
          ./migration-scripts/migrate-repos-from-list-base-ghec2ghec.sh $GHEC_USER_NAME $GHEC_USER_PAT $GHEC_SOURCE_ORG_NAME $GHEC_TARGET_ORG_NAME $GHEC_MAIN_BRANCH
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
