name: Migrate GHEC Org1 repo to GHEC Org2 repo

on: workflow_dispatch

env:
  GHEC_USER_NAME: ${{ secrets.GHEC_USER_NAME }}
  GHEC_USER_PAT: ${{ secrets.GHEC_USER_PAT }}
  GHEC_SOURCE_ORG_NAME: ${{ secrets.GHEC_SOURCE_ORG_NAME }}
  GHEC_TARGET_ORG_NAME: ${{ secrets.GHEC_TARGET_ORG_NAME }}
  GHEC_MAIN_BRANCH: ${{ secrets.GHEC_MAIN_BRANCH }}
  GH_TOKEN: ${{ github.token }}

jobs:
  GHES-to-GitHub:
    name: Migrate from GHES to GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Migrate repos
        run: |
          chmod a+x ./migration-scripts/migrate-repos-from-list-base-ghec2ghec.sh
          ./migration-scripts/migrate-repos-from-list-base-ghec2ghec.sh $GHEC_USER_NAME $GHEC_USER_PAT $GHEC_SOURCE_ORG_NAME $GHEC_TARGET_ORG_NAME $GHEC_MAIN_BRANCH
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
