name: Migrate GHES repo to GitHub

on: workflow_dispatch

env:
  # Github Enterprise Server config
  GHES_USER_NAME: ${{ secrets.GHES_USER_NAME }}
  GHES_USER_PASSWORD: ${{ secrets.GHES_USER_PASSWORD }}
  GHES_ORG_NAME: ${{ secrets.GHES_ORG_NAME }}
  GHES_HOST: ${{ secrets.GHES_HOST }}
  # Github Enterprise Cloud config
  GHEC_USER_NAME: ${{ secrets.GHEC_USER_NAME }}
  GHEC_USER_PAT: ${{ secrets.GHEC_USER_PAT }}
  GHEC_ORG_NAME: ${{ secrets.GHEC_ORG_NAME }}
  GHEC_MAIN_BRANCH: ${{ secrets.GHEC_MAIN_BRANCH }}

jobs:
  GHES-to-GitHub:
    name: Migrate from GHES to GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Migrate repos
        run: |
          ./migration-scripts/migrate-repos-from-list-base-ghes2ghec.sh $GHES_USER_NAME $GHES_USER_PASSWORD $GHES_ORG_NAME $GHES_HOST $GHEC_USER_NAME $GHEC_USER_PAT $GHEC_ORG_NAME $GHEC_MAIN_BRANCH
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
